version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/app"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "com.simplecityapps:recyclerview-fastscroll"
    allow:
      - dependency-type: "direct"
