version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/app"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 100
    allow:
      - dependency-type: "direct"
    labels:
      - "dependencies"
      - "automatic-merge"
