sudo: false

language: android

machine:
  environment:
    _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
    GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"

jdk:
- oraclejdk8

android:
  components:
  - tools
  - build-tools-29.0.2
  # the same SDK has to be configured in app/build.gradle:
  - android-28
  - extra-android-support
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
  - android-sdk-build-tools-.+

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

script: "./gradlew assemble"

deploy:
  provider: releases
  api_key:
    secure: WcflHJGPWnNpx/1mcIRRf5zTw7t+xj/lq2RVVxC3upAerxYOEdpe1bqYgo0WAfwTd+U+IfFNANKDPjIyECjKx/2B9prnUIQ/janlV2rGa+x2VW7imipYIJwz5AQ6g8XLN5mrqS1RKtf24moj3EsFLJAZFq6auZgwij4mKzbOt0taY5ujl4sXwOxQoh79AtHr26kfrwNksugJ/5f1n1AZx+qVt7HsGhBMyTx7uPLbE6eelO0fvf20u/7PubgwMrJlTse/D4BI+LL1GvLv4R50u6vgwkRoJZsUjVNgcpr5vRJhWRD8IZHWmxraUJWF9adEp5UZ/1nPf4joIPddoH15g/KTvtTE3knKCgYtIHNyX/HnOJq7ujGlON/JqoZPV51uxoujCpnpH5htJhhYEO3kvwlmB3y5EuYxBZiL1rogw0ljzL3Pwp3gVFyRUe1oK9ucl4IegbZbXZxgCavvjd6j1sYDmpDeG5SJcclpIs+QzHhx5AD0gOnbdyGlbg317mIwXN1xBSYGKr4cNFI2VS7StNyWMmc3hd4U9AC93MnrixIGK81zmE6s0Xg0hSOsNgFHWAkmIQAfl4m7UF0caK/jezRf3TI1wNVSxpMRrRlUDP5Ik/ny5YxdRWVFMQ+YLzW6liG0WGzyqn2ybk4yuuowuEL6YN8qsXo2X1FV8vmUPsg=
  file: "./app/build/outputs/apk/release/*.apk"
  file_glob: true
  skip_cleanup: true
  on:
    repo: mathisdt/sdbviewer
    tags: true
