name: Build

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"

jobs:
  build:
    uses: mathisdt/workflows/.github/workflows/android.yaml@master
    with:
      changelog-link: https://zephyrsoft.org/sdbviewer/history
    secrets: inherit
